import mongoose from "mongoose";
const productSchema=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    images:[],
    category:{
        type:mongoose.Types.ObjectId,
        ref:"Category",
        required:true,
    },
    subCategory:{
        type:mongoose.Types.ObjectId,
        ref:"SubCategory",
        required:true,
    },
    mrp:{
        type:Number,
        required:true,
    },
    sellingPrice:{
        type:Number,
        required:true,
    },
    deliveryCharges:{
        type:Number,
        required:true,
    },
    stock:{
        type:Number,
        required:true
    },
    warranty:{
        type:String,
        required:true,
    },
    replacementDays:{
        type:Number,
        required:true,
    },
    deliveryDays:{
        type:Number,
        required:true,
    },
    specificationName:[],
    specification:[],
    productDescription:{
        type:String,
    },
    reviews:[{
        type:mongoose.Types.ObjectId,
        ref:"Review"
    }],
    totalRating:{
        type:Number,
        default:0
    },
    numberOfReviews:{
        type:Number,
        default:0
    }
 
},{timestamps:true})
export default mongoose.model("Product",productSchema);

// 