import mongoose from "mongoose";
const userSchema=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    phone:{
        type:String,
        required:true,
    },
    password:{
        type:String,
        required:true,
    },
    referralCode:{
        type:mongoose.Types.ObjectId,
        ref:"ReferralCode"
    },
    referredBy:{
        type:mongoose.Types.ObjectId,
        ref:"ReferralCode"
    },
    cashbackEarned:{
        type:String,
    },
    withdrawlHistory:[],
    intrests:[{
        type:mongoose.Types.ObjectId,
        ref:"Category"
    }],
    cart:[],
    wishlist:[{   
        type:mongoose.Types.ObjectId,
        ref:"Product"
    }],
    savedForLater:[{
        type:mongoose.Types.ObjectId,
        ref:"Product"
    }],
    productsBaught:[],
    addresses:[ {
        type:mongoose.Types.ObjectId,
        ref:"Address"
    }],
    orders:[{
        type:mongoose.Types.ObjectId,
        ref:"Order"
    }],
    cancelledProducts:[{
        type:mongoose.Types.ObjectId,
        ref:"CancelledProduct"
    }],
    reviews:[{type:mongoose.Types.ObjectId,
        ref:"Review"
    }],
    role:{
        type:String,
        enum:["user","admin"],
        default:"user"
    }
},{timestamps:true})
export default mongoose.model("User",userSchema);

// 